{% set version = "1.1.1" %}

package:
  name: jupyter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter/jupyter-{{ version }}.tar.gz
  sha256: d55467bceabdea49d7e3624af7e33d59c37fff53ed3a350e1ac957bed731de7a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - ipykernel
    - ipywidgets
    - jupyter_console
    - jupyterlab
    - nbconvert-core
    - notebook
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    # check jupyter works
    - jupyter --help
  imports:
    - jupyter

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter metapackage. Install all the Jupyter components in one go.'
  dev_url: https://github.com/jupyter/jupyter

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - xylar
