{% set version = "1.0.0" %}

package:
  name: jupyter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter/jupyter-{{ version }}.tar.gz
  sha256: d9dc4b3318f310e34c82951ea5d6683f67bed7def4b259fafbfe4f1beb1d8e5f

build:
  noarch: python
  number: 10
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter_core
    - pip
    - python >=3.6
  run:
    - ipykernel
    - ipywidgets
    - jupyter_console
    - nbconvert
    - notebook
    - python >=3.6
    - qtconsole-base

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # check jupyter works
    - jupyter --help
  imports:
    - jupyter

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter metapackage. Install all the Jupyter components in one go.'
  dev_url: https://github.com/jupyter/jupyter

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - xylar
