{% set version = "1.0.0" %}

package:
  name: jupyter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter/jupyter-{{ version }}.tar.gz
  sha256: d9dc4b3318f310e34c82951ea5d6683f67bed7def4b259fafbfe4f1beb1d8e5f

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - python                               # [build_platform != target_platform]
    - pip                                  # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - notebook
    - qtconsole         # [(x86 or x86_64) and python_impl == "cpython"]
    - jupyter_console
    - nbconvert
    - ipykernel
    - ipywidgets

test:
  commands:
    - jupyter --help
    - jupyter nbextension list

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter metapackage. Install all the Jupyter components in one go.'
  dev_url: https://github.com/jupyter/jupyter

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - xylar
